name: Secrets and Variables

on:
    workflow_dispatch

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Printing my name from secrets
              run: echo " API Key = ${{ secrets.API_KEY }} "
