name: Secrets and Variables

on:
    workflow_dispatch

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Printing api key from secrets
              run: echo " API Key = ${{ secrets.API_KEY }} "

            - name: Printing DB Password from secrets 
              run: echo "DB PASSWORD = ${{ secrets.DB_PASSWORD }}"

            - name: Printing my name from variables
              run: echo "My Name = ${{ vars.MY_NAME }}"
            
            - name: Printing the app name from variables
              run: echo "My App name = ${{ vars.APP_NAME }}"